# Generated by Django 3.2.3 on 2021-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='firstmodel',
            name='password',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
