# Generated by Django 3.2.3 on 2021-06-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raju', '0004_auto_20210628_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
