# Generated by Django 3.2.3 on 2021-06-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Raju', '0005_useritem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='password',
        ),
    ]
