# Generated by Django 3.2.3 on 2021-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Raju', '0006_remove_useritem_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informn',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='informn',
            name='url',
        ),
        migrations.AddField(
            model_name='informn',
            name='emotion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='informn',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
